### ISSUE TITLE
상품 리포지토리 만들기

### ISSUE THREAD

**Issue by daengdaengLee** [daengdaengLee/until#10]
related issue : #4 
related branch : feat/item-repository

## 할 일 

- 상품 엔티티 객체에 JPA 애노테이션으로 DB 매핑 정보 추가하기
- 상품 리포지토리 객체 만들기 (ex `interface UserRepository extends JpaRepository<Long, Item> { ... }`)

## 주의

- ~~feat/item-entity 브랜치로부터 진행중~~
- ~~이후 feat/item-entity 브랜치를 먼저 develop 에 머지한 후 이후 커밋들만 develop 뒤로 cherry-pick 하여 진행해야 함~~
- 처리 완료

**Comment by daengdaengLee** [comment]
@tableMinPark 님 이거 feat/item-repository 브랜치에 일단 작업했는데요.
확인해보시고 이상 없으면 상민님께서 PR 열어주시겠어요? :)

**Comment by tableMinPark** [comment]
> @tableMinPark 님 이거 feat/item-repository 브랜치에 일단 작업했는데요.
확인해보시고 이상 없으면 상민님께서 PR 열어주시겠어요? :)

@daengdaengLee @Repository 어노테이션이 없어서 추가하고 올리겠습니다. :)
