### ISSUE TITLE
상품 생성 서비스 만들기

### ISSUE THREAD

**Issue by daengdaengLee** [daengdaengLee/until#12]
## 개요

- 상품을 생성할 수 있는 서비스 객체를 만든다.

## 개발 사항

- ItemService 만들기
- create 메소드 만들기
- Input: Item, Output: Item
- 단위 테스트 작성하기 (**Spring 테스트 안 쓰고 순수 단위 테스트로**)

**Comment by daengdaengLee** [comment]
@tableMinPark 님 혹시 괜찮으시면 #10 번 이슈 완료되면, 이 내용 진행해서 PR 올려주실 수 있을까요?

**Comment by tableMinPark** [comment]
> @tableMinPark 님 혹시 괜찮으시면 https://github.com/daengdaengLee/until/issues/10 번 이슈 완료되면, 이 내용 진행해서 PR 올려주실 수 있을까요?

지금 바로 진행해서 올리겠습니다!

추가적으로 Item Entity에 @Builder, @AllArgsConstructor, @NoArgsConstructor 어노테이션이랑 
~~createdAt에 @CreationTimestamp, updatedAt에 @UpdateTimestamp 어노테이션~~ 추가하려고 하는데 괜찮을까요?

**Comment by daengdaengLee** [comment]
> 추가적으로 Item Entity에 @builder, @AllArgsConstructor, @NoArgsConstructor 어노테이션이랑

생성자 관련해서는 작업하시다가 필요할 때 그때그때 추가해주시면 될 것 같아요~
