### ISSUE TITLE
프로젝트 초기화

### ISSUE THREAD

**Issue by daengdaengLee** [daengdaengLee/until#2]
- 스프링 부트 프로젝트로 초기화
- 어떤 라이브러리를 추가할까요?
- 자바는 어떤 버전으로 할까요?

**Comment by daengdaengLee** [comment]
> * 자바는 어떤 버전으로 할까요?

자바는 현재 LTS 인 17버전으로 하는 게 좋을 것 같아요.

**Comment by daengdaengLee** [comment]
> * 스프링 부트 프로젝트로 초기화

- 처음에는 간단하게 단일 프로젝트 형태로 Initializr 에서 생성한 그대로 쓰는 게 좋을 것 같아요. 
- 빌드 툴은 Gradle - Groovy 가 좋을 것 같습니다.
- 스프링 부트 버전은 초기화하는 시점에서 최신 버전 쓰면 될 것 같아요.

**Comment by tableMinPark** [comment]
> - 어떤 라이브러리를 추가할까요?

- lombok은 어노테이션 사용하기 위해 필요할 것 같습니다.
- 단위 테스트를 분리된 환경에서 진행하기 위해서 h2도 추가하면 좋을 것 같습니다.

**Comment by daengdaengLee** [comment]
> * 어떤 라이브러리를 추가할까요?

- Spring Web
- Spring Data JPA
- Lombok
- Validation
- H2 Database (thanks @tableMinPark )

이 정도에서 시작하는 게 좋을 것 같아요.
나중에 구현할 기능 정하고 나서 필요한 라이브러리는 그때 추가하는 게 어떨까요?

**Comment by tableMinPark** [comment]
> - 어떤 라이브러리를 추가할까요?

좋은 것 같습니다. 이후에 h2는 단위 테스트를 진행할 때 추가해도 될 것 같습니다.

**Comment by daengdaengLee** [comment]
> > * 어떤 라이브러리를 추가할까요?
> 
> 좋은 것 같습니다. 이후에 h2는 단위 테스트를 진행할 때 추가해도 될 것 같습니다.

아! h2 도 포함하면 좋을 것 같아요. 제가 누락했네요..

**Comment by jinseong205** [comment]
> * 어떤 라이브러리를 추가할까요?

QueryDSL 도 추가하면 좋을것 같습니다.

**Comment by dudwns9280** [comment]
> 비교적 복잡한 쿼리를 사용할때 query DSL 사용도 좋을것 같습니다.

query DSL 도 좋지만 첫 project init라서 query DSL은 추후에 필요하다고 느끼면 추가하는게 좋을 것 같아요.

**Comment by daengdaengLee** [comment]
## 정리

- Java & Spring 프로젝트
- Java 17 버전 사용
- Spring Boot 3.1.3 버전 사용
- Gradle - Groovy 빌드 툴 사용
- Jar 패키징
- Group : hello, Artifact & Name : until, Package Name : hello.until
- Dependencies:
    - Lombok
    - Spring Web
    - Validation
    - Spring Data JPA
    - H2 Database

---

- 지금까지 코멘트 남겨주신 내용 간단하게 정리했습니다.
- 혹시 수정할 내용이 있으면 아래에 다시 코멘트 남겨주세요.
- 위 설정에 문제가 없으면 따봉 부탁드립니다. :)

**Comment by daengdaengLee** [comment]
- 위 코멘트 기준으로 프로젝트 생성했습니다.
- main, develop 브랜치 각각 만들어 두었습니다. 이후 작업은 develop 브랜치에서 작업 브랜치 생성해서 진행해주세요.
- 문제 없으면 이모지로 반응 부탁드립니다. 모두 확인하신 후에 이 이슈는 닫도록 하겠습니다.

@jinseong205 @dudwns9280 @tableMinPark
