### ISSUE TITLE
간단한 회원 entity 설계

### ISSUE THREAD

**Issue by dudwns9280** [daengdaengLee/until#5]
## 개요

간단한 회원 가입(인증 없이), 회원 정보 수정, 회원 정보 삭제, 회원 탈퇴 기능 구현하기 위한 User Entity 설계

## 정할 내용

1) 회원 entity

Entity Name: user
- id 
- 유저 email 
- 패스워드 
- 회원 가입 일자
- 회원 정보 수정 일자

## 정해진 내용

Entity Name: user
- id 
- 유저 email 
- 패스워드 
- 회원 가입 일자
- 회원 정보 수정 일자

더 추가하실 내용이 있으신가요?
@jinseong205

**Comment by jinseong205** [comment]
> 더 추가하실 내용이 있으신가요?

현재 상황에서는 크게 추가할 내용은 없을 거 같습니다.
회원 수정일자 넣는 것도 좋을 것 같습니다.

> 회원 가입 일자

해당 type은 LocalDateTime 을 이용 하는게 좋을까요?

**Comment by dudwns9280** [comment]
> > 더 추가하실 내용이 있으신가요?
> 
> 현재 상황에서는 크게 추가할 내용은 없을 거 같습니다. 회원 수정일자 넣는 것도 좋을 것 같습니다.

수정 일자 좋아보여요 추가하겠습니다~

> > 회원 가입 일자
> 
> 해당 type은 LocalDateTime 을 이용 하는게 좋을까요?

아 네네 LocalDateTime으로 생각하고 있었습니다
