### ISSUE TITLE
간단한 회원 생성 기능 설계

### ISSUE THREAD

**Issue by jinseong205** [daengdaengLee/until#7]
### 개요
회원가입을 위한 회원 정보 생성 기능 구현

### 내용

createUserRequest 를 생성 및 검증 내용 추가 예정
  - email ( email 여부 확인)
  - password  (8글자 이상 20자 이하)

controller , service각 anotation을 이용하여 빈으로 등록, jpaRepostiroy 상속 및 기능 구현 예정

해당 내용 정도를 추가하여 구현 예정입니다.
보완 할 내용 남겨주시면 감사하겠습니다. @dudwns9280

**Comment by dudwns9280** [comment]
## 추후 로그인 id는 무엇이 될까요??
회원 가입용도로 사용할 목적인데,
그럼 추후 로그인을 구현할 때 id는 Email이 되는건가요?

## 개인정보에 대한 고민
Email은 개인정보에 해당하나요?
password는 개인정보에 해당하나요?
Database에 적용할 때 그대로 넣는다면 어떤 문제점이 있을까요?

**Comment by jinseong205** [comment]
> 회원 가입용도로 사용할 목적인데,
> 그럼 추후 로그인을 구현할 때 id는 Email이 되는건가요?

해당내용은 #5 에서 회의한 내용을 바탕으로 구현하다보니
email을  로그인 id로 생각하고 생성하였습니다.
별도의 아이디가 필요하다면 로그인을 위한 컬럼을 추가하는 방식이 필요할 것 같네요

> Email은 개인정보에 해당하나요?
> password는 개인정보에 해당하나요?
> Database에 적용할 때 그대로 넣는다면 어떤 문제점이 있을까요?

Email과 Password는 개인정보가 맞다고 생각합니다.
그대로 저장된다면 개인정보 노출에 대한 위험이 있다고 생각합니다.
패스워드의 경우에는 필수적인 암호화가 있어야 될 거 같습니다.
