### ISSUE TITLE
Spring Security 적용

### ISSUE THREAD

**Issue by jinseong205** [daengdaengLee/until#70]
### spring security 적용

- 기존 spring-security-crypto -> spring-security-starter 로 변경
- 모든 url 접근 허용
- csrf disable

추가적으로 필요한 부분이 있으면 코멘트 요청 드립니다.
추후 로그인 방식 구현과 관련된 내용도 남겨주시면 좋겠습니다.

**Comment by daengdaengLee** [comment]
저희 혹시 로그인 및 인증은 쿠키&세션 방식을 사용하나요, 아니면 JWT 같은 토큰 방식을 사용하나요?

**Comment by jinseong205** [comment]
아직 따로 얘기 나온건 없는데
토큰 방식을 이용하는것이 어떨까요?

**Comment by daengdaengLee** [comment]
좋습니다! 토큰 방식에서도 차이가 많더라구요.

- JWT 해석해서 문제 없으면 해당 토큰 내용으로 바로 인증 정보 생성
- JWT 해석해서 문제 없으면 해당 토큰 내용으로 DB 조회해서 인증 정보 생성
- JWT 가 유효한지 DB 에서 확인하고 해석해서 ... (위와 동일)

JWT 관련 라이브러리는 spring security 에서 제공하진 않아서 따로 추가해야 할 것 같습니다.
저는 jjwt 라이브러리 썼었어요.
이 라이브러리는 JWT 만들 때 비대칭키로 암호화시켜버리는 기능까지 제공하더라구요.

**Comment by jinseong205** [comment]
감사합니다. 참고하여 진행해보도록 하겠습니다.

> JWT 해석해서 문제 없으면 해당 토큰 내용으로 바로 인증 정보 생성

제가 생각 한 부분은 해당 부분까지만 생각했었습니다.
추가적인 부분은 진행하고 추가하는 방식으로 가면 좋을것 같습니다
spring security 적용 하고 이후 jwt 토큰을 이용한 로그인 과정 진행하도록 하겠습니다.
