### ISSUE TITLE
간단한 회원 단건 조회 기능 설계

### ISSUE THREAD

**Issue by jinseong205** [daengdaengLee/until#8]
개요
회원 단건 조회 기능 구현

내용
retrieveUserResponse 유저 정보 조회 dto 생성예정
controller , service, repository에 각 기능 구현 예정

해당 내용 정도를 구현 예정입니다.
보완 할 내용 남겨주시면 감사하겠습니다. @dudwns9280

**Comment by dudwns9280** [comment]
get이나 Find가 아닌 retrieve라는 단어를 사용하신 이유가 있으실까요?

**Comment by jinseong205** [comment]
> get이나 Find가 아닌 retrieve 라는 단어를 사용하신 이유가 있으실까요?

큰 이유는 없고 그 전 회사에서 주로 사용했어서 익숙해서 사용한거같네요.
get이나 find가 더 일반적 인거 같네요. find로 변경하여 작성하겠습니다

**Comment by dudwns9280** [comment]
get과 find중에 왜 find를 선택하셨을까요?

**Comment by jinseong205** [comment]
get/find 사용 용도를 좀 더 찾아봤는데 사용하는 용도가 좀 다른거 같네요.
해당 상황에서는 get이 더 맞는 상황인거 같네요.
해당 getUserRespone로 사용하느넥 더 좋을거 같습니다.
