### ISSUE TITLE
상품 엔티티 객체 만들기

### ISSUE THREAD

**Issue by daengdaengLee** [daengdaengLee/until#9]
related issue : #4 
related branch : feat/item-entity

## 개요

- 상품 엔티티 객체를 만듭니다.
- 현재 시점에서 필요한 최소한의 데이터와 메소드만 정의합니다.

## 정할 내용

- 패키지 및 엔티티 이름은 뭘로 할까요? 우선 `item` 이라고 했는데 다른 더 좋은 이름이 있으면 수정해주세요~

@tableMinPark

**Comment by daengdaengLee** [comment]
@tableMinPark 님 `feat/item-entity` 브랜치의 내용 확인 후에 이상 없으면 코멘트 남겨주세요.
이후에 PR 생성해요~

**Comment by tableMinPark** [comment]
@daengdaengLee 확인했습니다!
